exp:
  config_dir: configs
  config: td_single_ffhq.yaml
  project: test_project
  tags:
    - None
  name: test_run_nada
  seed: 12
  root: .
  notes: empty notes
  logging: true
  step_save: 25
  trainer: td_single
training:
  iter_num: 250
  batch_size: 4
  device: cuda:0
  generator: stylegan2
  phase: all
  patch_key: original
  source_class: Human
  target_class: The Joker
  no_coarse: True
  auto_layer_k: 16
  auto_layer_iters: 0
  auto_layer_batch: 8
  mixing_noise: 0.9
optimization_setup:
  visual_encoders: 
    - ViT-B/32
    - ViT-B/16
  loss_funcs:
    - direction
    - indomain
  loss_coefs:
    - 1.0
    - 0.25
  g_reg_every: 4
  optimizer:
    weight_decay: 0.0
    lr: 0.002
    betas:
    - 0.0
    - 0.999
generator_args:
  checkpoint_path: pretrained/StyleGAN2/stylegan2-ffhq-config-f.pt
evaluation:
  is_on: false
  vision_models:
    - ViT-L/14
  step: 20
  data_size: 500
  batch_size: 12
logging:
  log_every: 10
  log_images: 20
  latents_to_edit: []
  truncation: 0.7
  num_grid_outputs: 1
checkpointing:
  is_on: false
  start_from: false
  step_backup: 100000